version: '3.7'

networks:
  internal:
    name: internal

services:
  app:
    container_name: fastapi
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - internal